### PR TITLE
Cross-compile arm64 images

### PR DESCRIPTION
**Pull request by SpComb**
Use `GOARCH=arm64` to cross-compile arm64 images.

These builds lack CGO support, which means no systemd journal support.

### CODE REVIEW

**Comment by SpComb** [comment]
Replacing the quay.io repo with separate per-arch repos:

* https://quay.io/repository/kontena/pharos-host-upgrades-amd64
* https://quay.io/repository/kontena/pharos-host-upgrades-arm64

**Comment by SpComb** [comment]
Tested that the `ARCH=arm64` builds work with `qemu-aarch64-static`:

```
docker run --rm -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static kontena/pharos-host-upgrades:arm64 pharos-host-upgrades --help
Usage of /bin/pharos-host-upgrades:
  -alsologtostderr
    	log to standard error as well as files
  -config-path string
    	Path to configmap dir (default "/etc/host-upgrades")
  ...
 ```

**Comment by jakolehm** [comment]
> These builds lack CGO support, which means no systemd journal support.

What does this mean? What kind of functionality we loose here?

**Comment by SpComb** [comment]
>> These builds lack CGO support, which means no systemd journal support.
> 
> What does this mean? What kind of functionality we loose here?

If the `apt-get update` or `unattended-upgrades` fails with an error, then you can't see those errors from kube. You need to SSH to the host and use `journalctl -u host-upgrades` instead.

**Pull request merged**
